package xray

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// Parameter keys shared across strategies. Operator-facing (transport) ones
// appear in Params(); Reality keys are generated by the provider and merged in.
// Per-client credentials (uuid/password) live in Client, not Params.
const (
	pPort = "port"
	// pUUID/pPassword are the single-credential keys used only for relay specs
	// (a relay dials with one credential). Instance clients carry their own.
	pUUID        = "uuid"
	pPassword    = "password"
	pSNI         = "sni"          // Reality serverName / TLS SNI
	pDomain      = "domain"       // TLS server cert domain
	pDest        = "dest"         // Reality steal-target host:port
	pRealityPriv = "reality_priv" // base64 x25519 private
	pRealityPub  = "reality_pub"  // base64 x25519 public
	pShortID     = "reality_sid"
	pCertPath    = "cert_path"
	pKeyPath     = "key_path"
	pWSPath      = "ws_path"
	pGRPCService = "grpc_service"
	pSSMethod    = "ss_method"
)

func portOf(p Params, def string) int {
	n, _ := strconv.Atoi(p.get(pPort, def))
	return n
}

func tlsSettings(p Params) map[string]any {
	return map[string]any{
		"serverName": p.get(pDomain, ""),
		"certificates": []any{map[string]any{
			"certificateFile": p.get(pCertPath, "/etc/xray/tls/cert.pem"),
			"keyFile":         p.get(pKeyPath, "/etc/xray/tls/key.pem"),
		}},
	}
}

// VlessClients builds settings.clients for VLESS from the client list.
// Exported for reuse by file-based modules (filemodule.go) whose
// "client_format" is "vless" -- flow is left empty by that path (the most
// broadly compatible option; "xtls-rprx-vision" is specific to raw
// TCP+Reality/TLS-vision and stays a compiled-strategy-only choice).
func VlessClients(clients []Client, flow string) []any {
	out := make([]any, 0, len(clients))
	for _, c := range clients {
		// Xray-core rejects an "encryption" key inside inbound VLESS
		// clients ("VLESS clients: \"encryption\" should not be in
		// inbound settings") -- confirmed live against xray 26.3.27.
		// It only belongs in the outbound/client-link side.
		m := map[string]any{"id": c.UUID}
		if flow != "" {
			m["flow"] = flow
		}
		out = append(out, m)
	}
	return out
}

// VmessClients builds settings.clients for VMess. Exported for reuse by
// file-based modules ("client_format": "vmess").
func VmessClients(clients []Client) []any {
	out := make([]any, 0, len(clients))
	for _, c := range clients {
		out = append(out, map[string]any{"id": c.UUID})
	}
	return out
}

// TrojanClients builds settings.clients for Trojan. Exported for reuse by
// file-based modules ("client_format": "trojan").
func TrojanClients(clients []Client) []any {
	out := make([]any, 0, len(clients))
	for _, c := range clients {
		out = append(out, map[string]any{"password": c.Password})
	}
	return out
}

func vlessLink(uuid, host string, port int, q url.Values, name string) string {
	u := url.URL{Scheme: "vless", User: url.User(uuid), Host: hostPort(host, port), RawQuery: q.Encode(), Fragment: name}
	return u.String()
}

func trojanLink(pw, host string, port int, q url.Values, name string) string {
	u := url.URL{Scheme: "trojan", User: url.User(pw), Host: hostPort(host, port), RawQuery: q.Encode(), Fragment: name}
	return u.String()
}

func hostPort(host string, port int) string { return host + ":" + strconv.Itoa(port) }

func needClients(clients []Client) error {
	if len(clients) == 0 {
		return fmt.Errorf("at least one client is required")
	}
	return nil
}

// ===== 1. VLESS + Reality over TCP =====

type realityVlessTCP struct{}

func (realityVlessTCP) Name() string      { return "reality-vless-tcp" }
func (realityVlessTCP) Label() string     { return "VLESS + Reality (TCP) — max stealth" }
func (realityVlessTCP) Cred() CredKind    { return CredUUID }
func (realityVlessTCP) MultiClient() bool { return true }
func (realityVlessTCP) InstanceSecrets() []SecretSpec {
	return []SecretSpec{
		{Key: pRealityPriv, Kind: "reality_keypair", PairKey: pRealityPub},
		{Key: pShortID, Kind: "short_id"},
	}
}
func (realityVlessTCP) Params() []ParamSpec {
	return []ParamSpec{
		{Key: pPort, Label: "Listen port", Default: "443", Required: true},
		{Key: pSNI, Label: "Camouflage SNI (real TLS site)", Placeholder: "www.microsoft.com", Required: true},
		{Key: pDest, Label: "Steal-from target host:port", Placeholder: "www.microsoft.com:443", Required: true},
	}
}
func (realityVlessTCP) BuildInbound(p Params, clients []Client) (map[string]any, error) {
	if err := requireParams(p, realityVlessTCP{}.Params()); err != nil {
		return nil, err
	}
	if err := needClients(clients); err != nil {
		return nil, err
	}
	if p.get(pRealityPriv, "") == "" {
		return nil, fmt.Errorf("reality private key must be provisioned")
	}
	return map[string]any{
		"listen":   "0.0.0.0",
		"port":     portOf(p, "443"),
		"protocol": "vless",
		"settings": map[string]any{"clients": VlessClients(clients, "xtls-rprx-vision"), "decryption": "none"},
		"streamSettings": map[string]any{
			"network":  "tcp",
			"security": "reality",
			"realitySettings": map[string]any{
				"show":        false,
				"dest":        p.get(pDest, ""),
				"serverNames": []any{p.get(pSNI, "")},
				"privateKey":  p.get(pRealityPriv, ""),
				"shortIds":    []any{p.get(pShortID, "")},
			},
		},
	}, nil
}
func (realityVlessTCP) ClientLink(p Params, c Client, host string) (string, error) {
	if p.get(pRealityPub, "") == "" {
		return "", fmt.Errorf("reality public key missing")
	}
	q := url.Values{}
	q.Set("security", "reality")
	q.Set("encryption", "none")
	q.Set("type", "tcp")
	q.Set("sni", p.get(pSNI, ""))
	q.Set("fp", "chrome")
	q.Set("pbk", p.get(pRealityPub, ""))
	q.Set("sid", p.get(pShortID, ""))
	q.Set("flow", "xtls-rprx-vision")
	return vlessLink(c.UUID, host, portOf(p, "443"), q, linkName(c, host)), nil
}

// ===== 2. VLESS + XTLS-Vision over TLS =====

type vlessVisionTLS struct{}

func (vlessVisionTLS) Name() string      { return "vless-vision-tls" }
func (vlessVisionTLS) Label() string     { return "VLESS + Vision (TLS)" }
func (vlessVisionTLS) Cred() CredKind    { return CredUUID }
func (vlessVisionTLS) MultiClient() bool { return true }
func (vlessVisionTLS) Params() []ParamSpec {
	return []ParamSpec{
		{Key: pPort, Label: "Listen port", Default: "443", Required: true},
		{Key: pDomain, Label: "TLS domain (your cert)", Placeholder: "vpn.example.com", Required: true},
		{Key: pCertPath, Label: "Cert file path", Default: "/etc/xray/tls/cert.pem"},
		{Key: pKeyPath, Label: "Key file path", Default: "/etc/xray/tls/key.pem"},
	}
}
func (vlessVisionTLS) BuildInbound(p Params, clients []Client) (map[string]any, error) {
	if err := requireParams(p, vlessVisionTLS{}.Params()); err != nil {
		return nil, err
	}
	if err := needClients(clients); err != nil {
		return nil, err
	}
	return map[string]any{
		"listen":   "0.0.0.0",
		"port":     portOf(p, "443"),
		"protocol": "vless",
		"settings": map[string]any{"clients": VlessClients(clients, "xtls-rprx-vision"), "decryption": "none"},
		"streamSettings": map[string]any{
			"network":     "tcp",
			"security":    "tls",
			"tlsSettings": tlsSettings(p),
		},
	}, nil
}
func (vlessVisionTLS) ClientLink(p Params, c Client, host string) (string, error) {
	q := url.Values{}
	q.Set("security", "tls")
	q.Set("encryption", "none")
	q.Set("type", "tcp")
	q.Set("sni", p.get(pDomain, host))
	q.Set("flow", "xtls-rprx-vision")
	return vlessLink(c.UUID, p.get(pDomain, host), portOf(p, "443"), q, linkName(c, host)), nil
}

// ===== 3. VMess + WebSocket + TLS (CDN) =====

type vmessWSTLS struct{}

func (vmessWSTLS) Name() string      { return "vmess-ws-tls" }
func (vmessWSTLS) Label() string     { return "VMess + WebSocket + TLS (CDN)" }
func (vmessWSTLS) Cred() CredKind    { return CredUUID }
func (vmessWSTLS) MultiClient() bool { return true }
func (vmessWSTLS) Params() []ParamSpec {
	return []ParamSpec{
		{Key: pPort, Label: "Listen port", Default: "443", Required: true},
		{Key: pDomain, Label: "TLS domain", Placeholder: "cdn.example.com", Required: true},
		{Key: pWSPath, Label: "WebSocket path", Default: "/ws"},
		{Key: pCertPath, Label: "Cert file path", Default: "/etc/xray/tls/cert.pem"},
		{Key: pKeyPath, Label: "Key file path", Default: "/etc/xray/tls/key.pem"},
	}
}
func (vmessWSTLS) BuildInbound(p Params, clients []Client) (map[string]any, error) {
	if err := requireParams(p, vmessWSTLS{}.Params()); err != nil {
		return nil, err
	}
	if err := needClients(clients); err != nil {
		return nil, err
	}
	return map[string]any{
		"listen":   "0.0.0.0",
		"port":     portOf(p, "443"),
		"protocol": "vmess",
		"settings": map[string]any{"clients": VmessClients(clients)},
		"streamSettings": map[string]any{
			"network":     "ws",
			"security":    "tls",
			"wsSettings":  map[string]any{"path": p.get(pWSPath, "/ws")},
			"tlsSettings": tlsSettings(p),
		},
	}, nil
}
func (vmessWSTLS) ClientLink(p Params, c Client, host string) (string, error) {
	domain := p.get(pDomain, host)
	conf := map[string]any{
		"v": "2", "ps": linkName(c, host), "add": domain, "port": strconv.Itoa(portOf(p, "443")),
		"id": c.UUID, "aid": "0", "scy": "auto", "net": "ws", "type": "none",
		"host": domain, "path": p.get(pWSPath, "/ws"), "tls": "tls", "sni": domain,
	}
	b, err := json.Marshal(conf)
	if err != nil {
		return "", err
	}
	return "vmess://" + base64.StdEncoding.EncodeToString(b), nil
}

// ===== 4. Trojan + TCP + TLS =====

type trojanTCPTLS struct{}

func (trojanTCPTLS) Name() string      { return "trojan-tcp-tls" }
func (trojanTCPTLS) Label() string     { return "Trojan (TLS)" }
func (trojanTCPTLS) Cred() CredKind    { return CredPassword }
func (trojanTCPTLS) MultiClient() bool { return true }
func (trojanTCPTLS) Params() []ParamSpec {
	return []ParamSpec{
		{Key: pPort, Label: "Listen port", Default: "443", Required: true},
		{Key: pDomain, Label: "TLS domain", Placeholder: "vpn.example.com", Required: true},
		{Key: pCertPath, Label: "Cert file path", Default: "/etc/xray/tls/cert.pem"},
		{Key: pKeyPath, Label: "Key file path", Default: "/etc/xray/tls/key.pem"},
	}
}
func (trojanTCPTLS) BuildInbound(p Params, clients []Client) (map[string]any, error) {
	if err := requireParams(p, trojanTCPTLS{}.Params()); err != nil {
		return nil, err
	}
	if err := needClients(clients); err != nil {
		return nil, err
	}
	return map[string]any{
		"listen":   "0.0.0.0",
		"port":     portOf(p, "443"),
		"protocol": "trojan",
		"settings": map[string]any{"clients": TrojanClients(clients)},
		"streamSettings": map[string]any{
			"network":     "tcp",
			"security":    "tls",
			"tlsSettings": tlsSettings(p),
		},
	}, nil
}
func (trojanTCPTLS) ClientLink(p Params, c Client, host string) (string, error) {
	q := url.Values{}
	q.Set("security", "tls")
	q.Set("type", "tcp")
	q.Set("sni", p.get(pDomain, host))
	return trojanLink(c.Password, p.get(pDomain, host), portOf(p, "443"), q, linkName(c, host)), nil
}

// ===== 5. Shadowsocks 2022 (single client) =====

type shadowsocks2022 struct{}

func (shadowsocks2022) Name() string      { return "shadowsocks-2022" }
func (shadowsocks2022) Label() string     { return "Shadowsocks 2022 (single client)" }
func (shadowsocks2022) Cred() CredKind    { return CredPassword }
func (shadowsocks2022) MultiClient() bool { return false }
func (shadowsocks2022) Params() []ParamSpec {
	return []ParamSpec{
		{Key: pPort, Label: "Listen port", Default: "8388", Required: true},
		{Key: pSSMethod, Label: "Cipher", Default: "2022-blake3-aes-128-gcm"},
	}
}
func (shadowsocks2022) BuildInbound(p Params, clients []Client) (map[string]any, error) {
	if err := requireParams(p, shadowsocks2022{}.Params()); err != nil {
		return nil, err
	}
	if err := needClients(clients); err != nil {
		return nil, err
	}
	return map[string]any{
		"listen":   "0.0.0.0",
		"port":     portOf(p, "8388"),
		"protocol": "shadowsocks",
		"settings": map[string]any{
			"method":   p.get(pSSMethod, "2022-blake3-aes-128-gcm"),
			"password": clients[0].Password,
			"network":  "tcp,udp",
		},
	}, nil
}
func (shadowsocks2022) ClientLink(p Params, c Client, host string) (string, error) {
	method := p.get(pSSMethod, "2022-blake3-aes-128-gcm")
	userinfo := base64.RawURLEncoding.EncodeToString([]byte(method + ":" + c.Password))
	return fmt.Sprintf("ss://%s@%s#%s", userinfo, hostPort(host, portOf(p, "8388")), linkName(c, host)), nil
}

// ===== 6. VLESS + gRPC + TLS =====

type vlessGRPCTLS struct{}

func (vlessGRPCTLS) Name() string      { return "vless-grpc-tls" }
func (vlessGRPCTLS) Label() string     { return "VLESS + gRPC + TLS" }
func (vlessGRPCTLS) Cred() CredKind    { return CredUUID }
func (vlessGRPCTLS) MultiClient() bool { return true }
func (vlessGRPCTLS) Params() []ParamSpec {
	return []ParamSpec{
		{Key: pPort, Label: "Listen port", Default: "443", Required: true},
		{Key: pDomain, Label: "TLS domain", Placeholder: "vpn.example.com", Required: true},
		{Key: pGRPCService, Label: "gRPC service name", Default: "grpc"},
		{Key: pCertPath, Label: "Cert file path", Default: "/etc/xray/tls/cert.pem"},
		{Key: pKeyPath, Label: "Key file path", Default: "/etc/xray/tls/key.pem"},
	}
}
func (vlessGRPCTLS) BuildInbound(p Params, clients []Client) (map[string]any, error) {
	if err := requireParams(p, vlessGRPCTLS{}.Params()); err != nil {
		return nil, err
	}
	if err := needClients(clients); err != nil {
		return nil, err
	}
	return map[string]any{
		"listen":   "0.0.0.0",
		"port":     portOf(p, "443"),
		"protocol": "vless",
		"settings": map[string]any{"clients": VlessClients(clients, ""), "decryption": "none"},
		"streamSettings": map[string]any{
			"network":      "grpc",
			"security":     "tls",
			"grpcSettings": map[string]any{"serviceName": p.get(pGRPCService, "grpc")},
			"tlsSettings":  tlsSettings(p),
		},
	}, nil
}
func (vlessGRPCTLS) ClientLink(p Params, c Client, host string) (string, error) {
	q := url.Values{}
	q.Set("security", "tls")
	q.Set("encryption", "none")
	q.Set("type", "grpc")
	q.Set("serviceName", p.get(pGRPCService, "grpc"))
	q.Set("sni", p.get(pDomain, host))
	return vlessLink(c.UUID, p.get(pDomain, host), portOf(p, "443"), q, linkName(c, host)), nil
}

func linkName(c Client, host string) string {
	if c.Name != "" {
		return c.Name
	}
	return host
}

func init() {
	Register(realityVlessTCP{})
	Register(vlessVisionTLS{})
	Register(vmessWSTLS{})
	Register(trojanTCPTLS{})
	Register(shadowsocks2022{})
	Register(vlessGRPCTLS{})
}
